#!/usr/bin/env node
/**
 * Codegen: snapshot the vendored `TheBookOfOhdsi` submodule into a static
 * TypeScript module so the server can load chapters on any runtime (Node,
 * Cloudflare Workers, Vercel Functions) without touching the filesystem or
 * shelling out to `git` at startup.
 */
import { execFile } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { parse as parseYaml } from "yaml";
import { z } from "zod";

const execFileAsync = promisify(execFile);

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const vendorDir = join(packageRoot, "vendor", "TheBookOfOhdsi");
const outputPath = join(packageRoot, "src", "generated", "content.ts");

const bookdownYamlSchema = z.object({
  rmd_files: z.array(z.string()),
});

async function resolveCommit(): Promise<string> {
  const { stdout } = await execFileAsync("git", ["rev-parse", "HEAD"], {
    cwd: vendorDir,
  });
  return stdout.trim();
}

async function readRmdList(): Promise<string[]> {
  const text = await readFile(join(vendorDir, "_bookdown.yml"), "utf8");
  return bookdownYamlSchema.parse(parseYaml(text)).rmd_files;
}

function tsStringLiteral(value: string): string {
  return JSON.stringify(value);
}

async function main(): Promise<void> {
  const commit = await resolveCommit();
  const rmdFiles = await readRmdList();

  const entries: Array<{ filename: string; body: string }> = [];
  for (const filename of rmdFiles) {
    const body = await readFile(join(vendorDir, filename), "utf8");
    entries.push({ filename, body });
  }

  const lines: string[] = [];
  lines.push(
    "// THIS FILE IS AUTO-GENERATED BY scripts/generate-content.ts.",
    "// Do not edit by hand; rerun `npm run generate-content` after updating",
    "// the vendor/TheBookOfOhdsi submodule.",
    "",
    `export const SOURCE_COMMIT = ${tsStringLiteral(commit)};`,
    "",
    "export const RMD_FILES: readonly string[] = Object.freeze([",
    ...rmdFiles.map((name) => `  ${tsStringLiteral(name)},`),
    "]);",
    "",
    "export const CHAPTER_BODIES: Readonly<Record<string, string>> = Object.freeze({",
  );
  for (const { filename, body } of entries) {
    lines.push(`  ${tsStringLiteral(filename)}: ${tsStringLiteral(body)},`);
  }
  lines.push("});", "");

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, lines.join("\n"), "utf8");

  const totalBytes = entries.reduce(
    (sum, entry) => sum + Buffer.byteLength(entry.body, "utf8"),
    0,
  );
  console.error(
    `[generate-content] ${entries.length} chapters, ${totalBytes} bytes, commit ${commit}`,
  );
  console.error(`[generate-content] wrote ${outputPath}`);
}

await main();
